module:
  # feature_extractor:
  #     _target_: models.model.Wav2vecWrapper
  # feature_extractor:
  #   _target_: models.ssl_trans.Upstream
  #   # _target_: models.ssl_trans.Featurizer
  model:
    _target_: models.ssl_trans.MTL
    # models.model.DirectRegressor, ChainModel, BiChain, EmbAttnRegressor, AttnRegressor
  proj_dim: 512
  shared_dim: 128
  tasks: country, voc, valence, arousal
  name_path: facebook/wav2vec2-large-xlsr-53
  feat_type: null
  output_stage: 1
  weighted_sum: 1
  dropout: 0
  mode: pf # f: frozen, pf: partial frozen, other: fully finetune
  chain_strategy: gt # pred, gt, ss
  # for init model
  sr: ${sr}
  max_wav_length: ${max_wav_length}
  task: ${task}

ckpt: null

criterion:
  _target_: models.loss.BaselineLoss
optimizer:
  _target_: torch.optim.AdamW
  lr: !!float 1e-3
  lr_ft: !!float 1e-5
  weight_decay: !!float 1e-3
batch_size: 256
