module:
  # feature_extractor:
  #     _target_: models.model.Wav2vecWrapper
  # feature_extractor:
  #   _target_: models.ssl_trans.Upstream
  #   # _target_: models.ssl_trans.Featurizer
  model:
    _target_: models.ssl_trans.MTL
    # models.model.DirectRegressor, ChainModel, BiChain, EmbAttnRegressor, AttnRegressor
  upstream: SpecFeature # Upstream, SpecFeature
  proj_dim: 64
  shared_dim: 128
  tasks: '' # country, voc, valence, arousal
  name_path: ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition
  feat_type: leaf
  num_heads: 2
  num_layers: 2
  depthwise_conv_kernel_size: 17
  output_stage: 1
  weighted_sum: 1
  dropout: 0.25
  mode: pf # f: frozen, pf: partial frozen, other: fully finetune
  chain_strategy: gt # pred, gt, ss
  # for init model
  sr: ${sr}
  max_wav_length: ${max_wav_length}
  task: ${task}

ckpt: null

criterion:
  _target_: models.loss.BaselineLoss
optimizer:
  _target_: torch.optim.AdamW
  lr: ${lr}
  lr_ft: 0
  weight_decay: !!float 1e-3
batch_size: 256
lr: !!float 1e-3
exp_name: ${module.model._target_}-${now:%m%d_%H%M}
